name: Build and push image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push by action
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: deeplythink/java-hello-world:latest-action
          platforms: linux/amd64,linux/arm64

      - name: Build and push by script
        run: |
          make image
